### ISSUE TITLE
Name is incorrectly consists of both first and last when signed in through GitHub

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-content#68]
![image](https://user-images.githubusercontent.com/1566470/43867420-07e34f04-9b1e-11e8-928b-ffb4bd54055a.png)

As a solution, just leave one name field instead of first and last names.

**Comment by n2pro** [comment]
@Woland2k  We can not do this because the git profile does not have a clear separation of the name and surname, and in order to initially create a user, we need to specify name from git profile. Therefore, we take for the value of the name in the git profile
In the future, the user can edit himself in this section  
![screenshot_21](https://user-images.githubusercontent.com/13115017/43902476-7ab792f2-9bea-11e8-95d7-1022f537a9a7.png)

**Comment by asvishnyakov** [comment]
@Woland2k It's bad practice to have First/Last name separated, if project is international. For example, Icelandic usually have only first name and patronym. Indonesian may have first and last name, first name & patronym, single-word name or even, only first name with multiple words.  In China first name is family name, while last name is personal name. And more. So the best solution is to have single field where user may write their full name in the way they prefer. For example, Sir Arthur Ignatius Conan Doyle or Kim Jong Un (and you need to call him Mr. Kim, not Mr. Un or Mr. Jong Un).

**Comment by Woland2k** [comment]
@asvishnyakov that's why in the ticket I specified "As a solution, just leave one name field instead of first and last names."

**Comment by asvishnyakov** [comment]
@Woland2k Ahah, sorry, just seemed it as part of garbage in footer. Banner blindness :)

**Comment by tatarincev** [comment]
@Tilesto I think we can leave only one input field `Name` then and bind it to the `user.fullName`.
